version: '3.7'

services:
  app:
    container_name: app
    restart: always
    build: .
    environment:
      NODE_ENV: development
      PORT: 4000
      POSTGRES_URL: postgresql://root:password@localhost:4001/app?schema=SCHEMA
    ports:
      - '4000:4000'
    links:
      - database
    volumes:
      - .:/app:delegated
    depends_on:
      - database
  database:
    container_name: database
    image: postgres
    restart: always
    ports:
      - '4001:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
