version: '3.7'

services:
  app:
    env_file: .env.dev
    command: npx npm-run-all prepare:server dev
    # restart: always
    build: .
    environment:
      NODE_CONFIG_DIR: /app/config # root, see Dockerfile
      NODE_ENV: development
      PORT: 3000
    ports:
      - '3000:3000'
    volumes:
      - .:/app:delegated
    depends_on:
      - database
  database:
    image: postgres:12
    env_file: .env.dev
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
